### ISSUE TITLE
Add the ability to replace / merge bookmarks when they are imported

### ISSUE THREAD

**Issue by lewadedun** [Dax89/harbour-webpirate#16]
Now they are just combined

**Comment by Dax89** [comment]
Do you mean, skip an url if it is already present in favorites?

**Comment by lewadedun** [comment]
Yes.
And add the ability to delete all bookmarks.
Sorry for my english :)

**Comment by Dax89** [comment]
Ok!
Don't worry, your english is very good :)

I will make this feature available for the next release.

**Comment by Dax89** [comment]
Favorites are now combined: you can import it in the same Folder Tree and you will not find duplicates :)
