### ISSUE TITLE
website address with just ip

### ISSUE THREAD

**Issue by millerii** [Dax89/harbour-webpirate#17]
If you use http address with just ip address, result is google search result. 

eg. http://81.209.95.237 should lead to google.fi, but istead of that, it will search that "string" with google.
What I'am really using is to go my home ip address where is like private web server/web interface.

**Comment by millerii** [comment]
clicking that link actually works but if you write it to addresbar, it will search that from google.

**Comment by Dax89** [comment]
It will be fixed for the next version.

Thanks for reporting!
