### ISSUE TITLE
Login prompt dialog missing

### ISSUE THREAD

**Issue by millerii** [Dax89/harbour-webpirate#19]
Some login prompt option is missing.
Some site should be login window, but instead that it skip it and straight away says unauthorized.

*emailed to you example site..

**Comment by Dax89** [comment]
Hi,
I didn't have received any email, but I think to know how to reproduce the issue :)

**Comment by millerii** [comment]
Typo in mail address.. say if you need it still.

**Comment by Dax89** [comment]
Hi, sorry for the delay.
I think that I have fixed the issue, you can email me the affected website if you want :)
