### ISSUE TITLE
Problems with lists  №2

### ISSUE THREAD

**Issue by lewadedun** [Dax89/harbour-webpirate#21]
Item from the list does not save position.
Always the first item
Reproduce here http://pda.finam.ru/analysis/charts/

Choose from 1. Press 2. There will always be "Polymetal"
![default](https://cloud.githubusercontent.com/assets/9382415/6093541/07cfd8e0-af25-11e4-94e9-98cdee29925c.jpg)

**Comment by Dax89** [comment]
Issue #18 fixes this

**Comment by lewadedun** [comment]
Version 0.9.3-1  - is not fixed. 
I told you that my English is not very good ))))
I meant that the list is not saved selected item: choose something in 1, press 2. Then again choose something in 1, and the list begins again with "Polymetal"....

**Comment by Dax89** [comment]
Ah, ok now it's clear :)
I reopen the issue, thanks for the clarification!

**Comment by lewadedun** [comment]
Ok ))
