### ISSUE TITLE
Screen blanking (power saving) enabled when playing back video

### ISSUE THREAD

**Issue by llelectronics** [Dax89/harbour-webpirate#25]
The screen blanking is kicking in even when the video player is playing some video. 
To avoid this you need some dbus magic. As sadly the nemomobile dbus qml import cannot be used (if you want to be harbour compliant, otherwise just import Sailfish.Media 1.0 and add    
     ScreenBlank { suspend: mediaPlayer.playbackState == MediaPlayer.PlayingState   } 

I wrote a little cpp helper that does basically the same. See https://github.com/llelectronics/webcat/commit/4f3ba4bb79fe513a78a456626fcf4bb34c191f35
Look out for ScreenBlank.qml and videohelper.hpp

**Comment by Dax89** [comment]
Thanks for this trick! :)
