### ISSUE TITLE
Downloads page not accessible

### ISSUE THREAD

**Issue by Moth2015** [Dax89/harbour-webpirate#27]
0.9.7-1: Details page for "Downloads" in ActionBar isn't accessible anymore. ActionBar gets closed instead.

**Comment by Dax89** [comment]
Mmmmh, I don't understand this issue, you could be more specific?
There is no "Downloads page" in the action bar.

**Comment by Moth2015** [comment]
Sorry, I meant "Sidebar", of course... :-D
I can't access the "Downloads"-section. Just me? ;-)

**Comment by Dax89** [comment]
Ah ok :+1:  :)

I have tried to open the Downloads page with no downloads and one download running, I don't have any issues and/or errors in runtime.

The issue could be in the filename detection algorithm that for some reason fails: do you experience this issue with every download?

You can try to execute WebPirate in a ssh session running "harbour-webpirate" command and see if Qml triggers some kind of error :)

**Comment by Moth2015** [comment]
Terminal drops this error on every attempt of accessing the "Download" section, no matter of type, size or quantity of downloads:

[W] unknown:439 - file:///usr/lib/qt5/qml
/Sailfish/Silica/PageStack.js:439: Error:
Error while loading page: file:///usr/sh
are/harbour-webpirate/qml/pages/downloadm
anager/DownloadsPage.qml:49 Type Download
ListItem unavailable
file:///usr/share/harbour-webpirate/qml/c
omponents/items/DownloadListItem.qml:96 L
oadingBar is not a type

**Comment by Dax89** [comment]
Thanks Moth!
I will fix it immediately and I will upload a new package in OpenRepos
