### ISSUE TITLE
Suggestion: Favicons in QuickGrid

### ISSUE THREAD

**Issue by Moth2015** [Dax89/harbour-webpirate#29]
... Favicons should survive deletion of private data. (IMHO)

**Comment by Dax89** [comment]
This is tricky, Favicons are stored in WebKit's database, but I will try to do it :)

**Comment by Moth2015** [comment]
Ah, I see. Never mind, it would just be a comfort feature without any priority. Good luck!

**Comment by plsng** [comment]
Isn't the point of deleting private data that it makes it look as if you've never used the browser before, so leaving favicons intact would indicate otherwise?

**Comment by Moth2015** [comment]
@plsng: That's a matter of opinion. Removed favicons indeed indicate a clean browsing experience, but on the other hand most browsers i know keep favicons for bookmarks and favorites after deletion of private data... :-)

**Comment by Dax89** [comment]
Implemented as an option!
You'll find it the upcoming v1.0 :)

**Be careful:** Favicon Database keeps visited domains, so, a partial navigation history is available.

**Comment by Moth2015** [comment]
Works very well. Thank you!
