### ISSUE TITLE
Pages remember your password, but does not remember login

### ISSUE THREAD

**Issue by lewadedun** [Dax89/harbour-webpirate#34]
Try saving login and password, then change the login , then spelled correctly. Correct login will not be saved.

**Comment by Dax89** [comment]
It happens in every website?

**Comment by lewadedun** [comment]
no.
For example https://tradematic.com/

**Comment by Dax89** [comment]
I have fixed something related to loading/saving login credentials.
Please, let me know if this issue is still present in 0.9.9-1 :)

**Comment by lewadedun** [comment]
ок.

**Comment by lewadedun** [comment]
Now it's ok!

**Comment by Dax89** [comment]
Perfect! :)

Bug Fixed in: e8ae80f3538becc6c039d4d9e832345fa8cf0085 (AES256 Cipher: Resize to the correct length)
