### ISSUE TITLE
I cant't download file from website

### ISSUE THREAD

**Issue by carmenfdezb** [Dax89/harbour-webpirate#35]
When I download a file from a website, for example .pdf file, I don't find the file. In 'Downloads' options I only find download.htm

**Comment by Dax89** [comment]
Hi,
It is possible to know the affected website so I can test it?

**Comment by carmenfdezb** [comment]
Well, It doesn't happend on all website. I've tested with some pages, and it works fine. I only have problems when I try to download bills in my telephone company.
![paint-03042015-103823](https://cloud.githubusercontent.com/assets/6286776/6980148/cf0efa56-d9ed-11e4-9d22-164f08f5a3e5.png)

**Comment by carmenfdezb** [comment]
I think I have problems when I try to download bills (.pdf file) from website which I have to log in. So I can't give you the URL.
I use WebPirate like the default browser in my jolla, because I like it very much, thank you for developing it.

**Comment by Dax89** [comment]
Ok, that's a good start!

Thanks for the info :)

**Comment by carmenfdezb** [comment]
Here you have an example:
https://www.dropbox.com/s/0ae7dk13ruds0x9/whatsup-0.1-2.armv7hl.rpm?dl=0
