### ISSUE TITLE
Share link in Twitter doesn't work fine

### ISSUE THREAD

**Issue by carmenfdezb** [Dax89/harbour-webpirate#39]
If I want to share a link in Twitter, I can't write anything in the text box.

**Comment by Dax89** [comment]
It seems to be a WebKit issue, also, it freezes the QtWebKit process.

I will try to use the integrated SaiflishOS "Share to..." feature for the next version

**Comment by carmenfdezb** [comment]
Ok, thank you very much ;)

**Comment by Dax89** [comment]
The commit 508fedaa33631f9dcedf20801c30e9150f0cef68 fixes the issue.

Now WebPirate uses integrated accounts (like Sailfish Browser) through DBus :)

**Comment by carmenfdezb** [comment]
Great!!! Goood news!!!
Thank you very much!!
