### ISSUE TITLE
Allow closing the last tab (and return to new tab by doing that)

### ISSUE THREAD

**Issue by Mikaela** [Dax89/harbour-webpirate#44]
I am not sure where I have gotten used to this behaviour, but returning to homepage from the only open tab feels difficult as it requires two touches instead of there being just the X for closing tab.

**Comment by Dax89** [comment]
Mmmh, do you want the last tab closable?
And, if the last tab is closed, WebPirate creates a new one with the selected home page?

**Comment by Mikaela** [comment]
YEs

**Comment by Dax89** [comment]
Ok!
