### ISSUE TITLE
Trying to authorize Tweetian just flashes the PIN and goes to error message.

### ISSUE THREAD

**Issue by Mikaela** [Dax89/harbour-webpirate#49]
I have Webpirate as default browser. When I attempt to login to Tweetian with the "open browser" button, I get the normal authirize or deny choice.

When I select Authorize, the page is there for too low amount of seconds and then moves to Twitter error message about some data missing.

*This report is a little bad, but I haven't had access to PC in days and GitHub Android vlient is a little doffocult oftrn.*

**Comment by Dax89** [comment]
It was an useragent issue, now WebPirate loads the "android version" of Twitter :)

**Comment by Mikaela** [comment]
When is the upcoming version planned in harbour?

**Comment by Dax89** [comment]
If testing goes well, I will send it in harbour this week.
