### ISSUE TITLE
I can't watch any video in Youtube with 1.5-1 version

### ISSUE THREAD

**Issue by carmenfdezb** [Dax89/harbour-webpirate#50]
I can't watch any video in Youtube, it shows: Protocol "rtsp" is unknown.

**Comment by Dax89** [comment]
You are clicking the "original" play button, which is not supported by the WebView :)
YouTube's grabber is triggered after ~1 second to ensure that the page is loaded.

Unfortunately, sometimes happens that the page is not "hacked" by the grabber in time, if this happens, try to reload the page, the grabber's "play" button looks different.

**Comment by carmenfdezb** [comment]
Ok. If I open the video in new tab, I see new play button, and see the video.

**Comment by Dax89** [comment]
A page refresh is enough, WebView needs to receive the "pageLoaded" event.

YouTube does not send that event because it modify the page's structure only and I use "urlChanged" event, which is not perfect :(

**Comment by carmenfdezb** [comment]
I closed WebPirate and opened it again, and now it's working fine.
Thank you for your attention, and for updating the app.

**Comment by Dax89** [comment]
:+1:
