### ISSUE TITLE
http:// appears in the source multiple times

### ISSUE THREAD

**Issue by Mikaela** [Dax89/harbour-webpirate#52]
* https://github.com/Dax89/harbour-webpirate/search?utf8=%E2%9C%93&q=http%3A%2F%2F

I am not sure if all of those should be http, but I would prefer my browser to do all queries with https. At least GitHub should be https and so should Gitorious (which doesn't exist anymore), with YouTube I am unsure as that might be related to downoader or the player.

The only instance that I am fully sure is https://github.com/Dax89/harbour-webpirate/pull/51, I don't want my queries to search engine go without https.

**Comment by Dax89** [comment]
Most of them can be changed to https:

1) Default Favorites: https://github.com/Dax89/harbour-webpirate/blob/256ccf2d007bf19f2a8b34952db06721276540bf/qml/js/settings/Favorites.js
2) YouTube Grabber: https://github.com/Dax89/harbour-webpirate/blob/6ba1af8958453df188a91685af11a75fda19512c/qml/js/youtube/YouTubeGrabber.js#L8
3) YouTube Cipher: https://github.com/Dax89/harbour-webpirate/blob/cec4ef92aece628288b65efe4ab79c5c139b6511/qml/js/youtube/YouTubeCipher.js#L59

Other ones are mainly regex and other data

**Comment by Dax89** [comment]
I can force https everywhere but, for example, if you go to JollaUsers using https protocol it doesn't load.
