### ISSUE TITLE
I can't play videos from Facebook

### ISSUE THREAD

**Issue by carmenfdezb** [Dax89/harbour-webpirate#66]
When I click to play video or long click to open in new tab, it doesn't do anything. So I can't watch videos from Facebook

**Comment by Dax89** [comment]
They never worked?

(I'm not on Facebook, that why I ask it :) )

**Comment by carmenfdezb** [comment]
I remember it was working in others versions of WebPirate, but I don't know when it failed.

**Comment by Dax89** [comment]
Probably Facebook or YouTube changed something.
It doesn't even trigger the grabber?

**Comment by carmenfdezb** [comment]
No, it doesn't. In webcat doesn't work now, only in jolla web browser

**Comment by llelectronics** [comment]
From what I know the last time it worked was when qtwebkit still had html5 audio and video support enabled. 
So it would need a special grabber for this. 
Though I am also not on facebook and cannot test or implement it either.

**Comment by Dax89** [comment]
@carmenfdezb:
This one: https://m.facebook.com/story.php?story_fbid=889027771139763&id=461284613914083&refsrc=https%3A%2F%2Fm.facebook.com%2Fvideo.php&_rdr 

can be a good sample for testing? :)

@llelectronics:
In order to bypass video/audio tags limitation, I grab the "src" attribute (if any) and I send its link to the integrated video player (when clicked), it seems that works very well!

**Comment by carmenfdezb** [comment]
Yeah, in WebPirate doesn't work. If I use Jolla web browser, it open new tab with this link:
https://video-mad1-1.xx.fbcdn.net/hvideo-prn2/v/t42.1790-2/10905589_889033081139232_1544703736_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InNkIn0%3D&oh=3ee80f149b04599615721c93d0b8685f&oe=5622D032

**Comment by Dax89** [comment]
:+1: 
That's an obfuscated video tag, it should be pretty easy to implement!

```
{
  "videoID": "889027771139763",
  "playerFormat": "inline",
  "playerOrigin": null,
  "rootID": 889027771139763,
  "playOnClick": true,
  "type": "video",
  "src": "https:\/\/video-mxp1-1.xx.fbcdn.net\/hvideo-prn2\/v\/t42.1790-2\/10905589_889033081139232_1544703736_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InNkIn0\u00253D&oh=3ee80f149b04599615721c93d0b8685f&oe=5622D032",
  "width": 310,
  "height": 175,
  "trackingNodes": "F"
}
```

Unescaped "src":
```
https://video-mxp1-1.xx.fbcdn.net/hvideo-prn2/v/t42.1790-2/10905589_889033081139232_1544703736_n.mp4?efg=eyJ2ZW5jb2RlX3RhZyI6InNkIn0%3D&oh=3ee80f149b04599615721c93d0b8685f&oe=5622D032
```

**Comment by carmenfdezb** [comment]
Great!!! Thank you!!

**Comment by llelectronics** [comment]
I closed the issue with a workaround to detect the **widePic** classname and then search for data-store attribute in its children to grab the json and get the video src. See: https://github.com/llelectronics/webcat/commit/fb54eb8012d0c917a9630c762f3a92988632eaf2

**Comment by Dax89** [comment]
Thanks! :)

**Comment by carmenfdezb** [comment]
Is this issue fixed in v1.9? I've installed last beta version, but it isn't working.

**Comment by Dax89** [comment]
I'm investigating, it seems that the page is slightly different when a user is logged in, I will push more fixes in the next beta

**Comment by carmenfdezb** [comment]
Great!! Thank you, dax89!!

**Comment by spider-fb** [comment]
what is this site ? "video-mxp1-1.xx.fbcdn.net"
How to get it through iptv "m3u8
