### ISSUE TITLE
Http Auth Dialog shows Password

### ISSUE THREAD

**Issue by dns2utf8** [Dax89/harbour-webpirate#68]
the Dialog for a HttpBasicAuth displays the Password

**Comment by Dax89** [comment]
Can you be more specific? How can I reproduce the issue (link or something else)?

**Comment by dns2utf8** [comment]
If you open a page with a http-basic authenthication like this: https://auth-demo.aerobatic.io/

You see your Password:
![screenshot-16-03-28-21-42-14](https://cloud.githubusercontent.com/assets/739070/14088182/509e6082-f52e-11e5-8d8f-5c779e850d40.png)

**Comment by Dax89** [comment]
Fixed in https://github.com/Dax89/harbour-webpirate/commit/f1e57231108e3d782c79f0f543000029431eb407

**Comment by dns2utf8** [comment]
Cool, thank you :+1:
