### ISSUE TITLE
Mobile Github.com menu button doesn't work

### ISSUE THREAD

**Issue by Tichy** [Dax89/harbour-webpirate#71]
This could be a webkit issue, since I saw a similar problem with Webcat, but not with the default (geko) browser.
In the mobile version of github, it's impossible to tap the (upper right) menu button.
![screenshot-16-02-15-12-09-40](https://cloud.githubusercontent.com/assets/2348771/13047244/f26031c4-d3dd-11e5-9255-f7403ce56de2.png)

**Comment by Dax89** [comment]
Are you using Sailfish 2.0.1.7?
I noticed this annoying issue after the update

**Comment by Tichy** [comment]
Nope, I'm still at 2.0.0.10 :)

**Comment by Dax89** [comment]
Ah, ok :)
I see what can I do, I don't have changed anything in the webview

**Comment by Mikaela** [comment]
Possibly related: https://github.com/Dax89/harbour-webpirate/issues/58

**Comment by Tichy** [comment]
I just tried to disable the integrated adblock and to restore my original /etc/hosts, so I can exclude those two.

**Comment by Dax89** [comment]
WebKit doesn't provide the WeakMap type:

```
[D] onConsoleLog:45 - https://assets-cdn.github.com/assets/mobile-c99e3b9fab9d48e38ac4c3094080d11cbd6c2a39aa8b17e9bea4cbccf249b6ef.js(1): ReferenceError: Can't find variable: WeakMap
```

**Comment by Dax89** [comment]
Solved with a polyfill: https://github.com/WebReflection/es6-collections
