### ISSUE TITLE
Doesn't open links from external apps when an instance is alredy open

### ISSUE THREAD

**Issue by Tichy** [Dax89/harbour-webpirate#72]
Web Pirate is set as default browser.

When I click a link on another app and Web Pirate is not open, it works fine: Web Pirate is launched and the link opened.

When I click a link on another app and Web Pirate is alredy opened, Web Pirate is brought to foreground but the link is not opened.

What I expect is that Web Pirate would be brought to foreground and the link opened in a new tab.

Tested with Feedly, Jolla Store and Warehouse as link sources.

**Comment by Dax89** [comment]
Mmmmh, it works as expected, at least in my case

**Comment by Tichy** [comment]
I tried launching it from terminal, to see if it prints out something useful, but instead I found something even stranger... if I first launch harbour-webpirate from the terminal everything works and every new link I from an external app, brings web pirate to foreground and the link in a new tab, but when I launch web pirate from launcher or from following a link, it behaves like I described above.

**Comment by Dax89** [comment]
Ah, ok!
I have tried launching it from Qt Creator, which is like opening it from terminal.
I will test it in the "standard way" later :)

In order to get logs from all applications it's sufficient to do:
```
journalctl -f
```

**Comment by Tichy** [comment]
I forgot again that Sailfish runs systemd :)

I did some new test with the new beta 1.9 and found something interesting. Maybe the problem is with Mimer. If I set WP as default browser within its own configuration everything works fine, but if I set it with Mimer, it shows the above issue.

**Comment by llelectronics** [comment]
Yeah that's why I don't recommend to set browsers as default with mimer. Mimer does not handle dbus stuff for your browser mainly because there is no standard and the browsers should and do implement it themselves.

**Comment by Dax89** [comment]
Thanks @llelectronics ! :)

@Tichy: Can I close this issue?

**Comment by Tichy** [comment]
Of course. It wasn't related to Web Pirate, in the end. :)

**Comment by Dax89** [comment]
Ok! :+1:
