### ISSUE TITLE
Avoid Lipstick clipboard stuck problem

### ISSUE THREAD

**Issue by llelectronics** [Dax89/harbour-webpirate#73]
I found a solution for the clipboard to be stucked on one entry that does not update no matter what you copy. This should address the issue some reported that our browsers can't copy text correctly. 
See my commit here: https://github.com/llelectronics/webcat/commit/011b0c7581c65ad8854bc44203da17fc9512755d

Positive side effect it unstucks the whole lipstick clipboard again so copying also works in other applications again. 
(Btw. already discussed upstream [means lipstick] patches in #sailfishos on irc. Hopefully they will land soon)

**Comment by Dax89** [comment]
Thanks Leszek!

I will include it when I finish the new UI.
Thanks again :)

**Comment by d9h02f** [comment]
Nice work!
