### ISSUE TITLE
Have cover actions

### ISSUE THREAD

**Issue by plsng** [Dax89/harbour-webpirate#8]
Like on Jolla's browser, it would be useful to have cover actions to open a new tab or refresh the current page. If you can think of other useful cover actions (maybe immediately open a specific bookmarked website?), please make it configurable!

**Comment by Dax89** [comment]
Mmmmh, I like configurable cover actions...
If you have some other nice ideas for covers, feel free to comment here, I will make them available in the next release :)

**Comment by plsng** [comment]
- An action that brings up the keyboard on the search engine field
- An action to wipe all browser data immediately (for the truly paranoid)
- An action to close the browser immediately
- The previous two actions combined? (although that could just be done by enabling 'Wipe data on exit' in settings and using the previous action)

**Comment by lewadedun** [comment]
good ideas! 
open a new tab or refresh the current page  -  first, please ))
