### ISSUE TITLE
Trouble opening URLs with Web Pirate as the default browser

### ISSUE THREAD

**Issue by JeffHoogland** [Dax89/harbour-webpirate#82]
I have web pirate set as the default browser using [Mimer](https://openrepos.net/content/llelectronics/mimer). When Web Pirate is closed and I click on a link in an email or other application it opens web pirate with the link as expected.

However - when web pirate is already open and I click on a URL in a different application - the application focus correctly changes back to web pirate, but the selected URL is not opened.

It must however Sailfish handles hyper links that is the issue - because if I run:

    harbour-webpirate http://google.com

From a terminal while Web Pirate is open - it opens the URL given in a new tab as expected.

Let me know if I can provide other information useful in debugging this or if there is a work around. I searched the issues but did not see anything like this.

**Comment by llelectronics** [comment]
Don't set the default Web application with mimer. It doesn't support the dbus magic that is necessary for this to work properly.

**Comment by JeffHoogland** [comment]
What is the proper way to make this the default web browser then?

**Comment by Dax89** [comment]
@JeffHoogland From WebPirate 2.x you can set it as default browser from settings.

**Comment by JeffHoogland** [comment]
Ahhh - I was still using version 1.7 from the Jolla store.

Thank you!
