### ISSUE TITLE
About page scrolls up too far

### ISSUE THREAD

**Issue by plsng** [Dax89/harbour-webpirate#9]
There seems to be whitespace at the bottom that shouldn't be there.

**Comment by plsng** [comment]
I see it probably has something to do with this latest commit: https://github.com/Dax89/harbour-webpirate/commit/cccb4429dd58a8d37a734e6c0e97c28a55138773

**Comment by Dax89** [comment]
Yeah, I know :)
I will fix it in the next version because is a low priority bug.
